[package]
name = "host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = { version = "16.0.0", features = ["component-model"] }
wasmtime-wasi = "16.0.0"
wasmtime-wit-bindgen = "16.0.0"
